/* Vocal Licks data: riffs, combos, progressions, vocabulary patterns. */
(function (root) {
  const D = {};

  /* ---- Crystal Cherelle's five building blocks (from her Riff Builder MIDI) ---- */
  const R = { qd: [.5, .25, .25], sl: [.5, .25, .25], sw: [.5, .25, .25, .125, .625], qdt: [1, .25, .25, 1], skip: [.5, 1, .25, .25, 1] };
  const V = { qd: [.85, .72, .64], sl: [.86, .8, .66], sw: [.86, .8, .74, .78, .82], qdt: [.84, .82, .8, .62], skip: [1, .82, .8, .8, .62] };
  function mk(steps) { const o = {}; for (const k in steps) o[k] = { n: steps[k], b: R[k], v: V[k] }; return o; }
  D.SETS = {
    minor: { name: "minor pentatonic", tonic: 64, scale: [0, 3, 5, 7, 10], minor: true,
      blocks: mk({ qd: [0, -1, -2], sl: [-2, -1, 0], sw: [-2, -1, 0, -1, 0], qdt: [0, -1, -2, -3], skip: [1, 0, -1, -2, -3] }) },
    blues: { name: "blues", tonic: 64, scale: [0, 3, 5, 7, 10], minor: true, shapeSet: "minor",
      blocks: Object.assign(mk({ qd: [0, -1, -2], sl: [-2, -1, 0], sw: [-2, -1, 0, -1, 0] }), {
        qdt: { n: [0, -1, -2, [-3, 1], -3], b: [1, .25, .25, .25, .25], v: [.84, .82, .8, .8, .62] },
        skip: { n: [1, 0, -1, -2, [-3, 1], -3], b: [.5, 1, .25, .25, .25, .75], v: [1, .82, .8, .8, .8, .62] } }) },
    major: { name: "major", tonic: 60, scale: [0, 2, 4, 5, 7, 9, 11], minor: false,
      blocks: mk({ qd: [2, 1, 0], sl: [0, 1, 2], sw: [0, 1, 2, 1, 2], qdt: [2, 1, 0, -1], skip: [4, 2, 1, 0, -1] }) },
    majpent: { name: "major pentatonic", tonic: 57, scale: [0, 2, 4, 7, 9], minor: false,
      blocks: mk({ qd: [3, 2, 1], sl: [1, 2, 3], sw: [1, 2, 3, 2, 3], qdt: [3, 2, 1, 0], skip: [4, 3, 2, 1, 0] }) }
  };
  D.BLOCKS = {
    qd: { name: "Quick Dip", num: 1, c: "var(--pink)", on: "var(--ink)", rhythm: "long, short, short",
      tip: "Three notes stepping down from home. Lean on the first note, then let the next two fall away quickly. She says any word or vowel works on it." },
    sl: { name: "Swift Lift", num: 2, c: "var(--blue)", on: "#fff", rhythm: "long, short, short",
      tip: "This is the Quick Dip turned upside down, three notes climbing back home with the same long-short-short rhythm." },
    sw: { name: "Swoopy Swift Lift", num: 3, c: "var(--green)", on: "var(--ink)", rhythm: "long, short, short, flick, hold",
      tip: "A Swift Lift with a small turn on top. Once you land, flick down one note and straight back up so the top note sounds twice, then hold it as long as you like." },
    qdt: { name: "Quick Dip Trip", num: 4, c: "var(--orange)", on: "var(--ink)", rhythm: "hold, short, short, land",
      tip: "A Quick Dip with one more note at the bottom. The first note gets a full beat, and the landing note can be short or held." },
    skip: { name: "Skip Quick Dip Trip", num: 5, c: "var(--yellow)", on: "var(--ink)", rhythm: "accent, hold, short, short, land",
      tip: "It starts above home and skips down to it, then runs the Quick Dip Trip. She sings that first note louder than the rest, which the accent mark shows." }
  };
  D.ORDER = ["qd", "sl", "sw", "qdt", "skip"];
  D.COMBOS = [
    { n: 1, b: ["qd", "sl"], note: "Down, then straight back up. The shared bottom note gets sung twice, so re-attack it cleanly." },
    { n: 2, b: ["qdt", "sl"], note: "She says these two fit together snugly. The lift starts one step above where the trip lands." },
    { n: 3, b: ["sl", "qdt"], note: "The same two blocks in the other order: climb home, then fall past it." },
    { n: 4, b: ["sw", "qdt"], note: "Combo 3 with more flair on top, since the swoop sets up the long note." },
    { n: 5, b: ["skip", "sl"], note: "The skip opens it, and the lift brings you back home at the end." },
    { n: 6, b: ["skip", "sw"], note: "Her favorite of the set. She calls the shape two little stairs.", sticker: "her favorite" },
    { n: 7, b: ["sl", "skip"], note: "She swapped in the plain Swift Lift here because the swoopy version felt clunky in front of the skip." },
    { n: 8, b: ["sl", "skip", "sw"], note: "All three chained, which she calls a melodic masterpiece. Learn combo 7 first.", sticker: "the big one" },
    { n: null, b: ["sw", "skip"], note: "She plays this order to show a join that doesn't work. The two halves sound separate. Listen for the gap, then compare with combo 7.", sticker: "listen for the gap", stickerCls: "blue" }
  ];

  /* ---- Chord progressions. beats: length of each chord in beats at "1 bar per chord". ---- */
  const BENNETT7 = { t: "7 super common chord progressions and why they work", u: "https://www.youtube.com/watch?v=Vyc8lezaa9g" };
  const BENNETT5 = { t: "5 popular chord progressions and why they work", u: "https://www.youtube.com/watch?v=cjOQIbkRQ-4" };
  const OMT = { t: "Open Music Theory: Blues-Based Schemas", u: "https://human.libretexts.org/Bookshelves/Music/Music_Theory/Open_Music_Theory_2e_(Gotham_et_al.)/07%3A_Popular_Music/7.08%3A_Blues-Based_Schemas" };
  D.PROGRESSIONS = [
    { id: "axis", group: "Pop & R&B", name: "Axis", chords: ["I", "V", "vi", "IV"], tonality: "major", src: BENNETT7,
      note: "The most famous four chords in pop. One pentatonic covers all of them." },
    { id: "otheraxis", group: "Pop & R&B", name: "The other Axis", chords: ["vi", "IV", "I", "V"], tonality: "major", src: BENNETT7,
      note: "The same four chords starting on vi, so it feels minor." },
    { id: "popnew", group: "Pop & R&B", name: "Pop's new favorite", chords: ["IV", "I", "vi", "V"], tonality: "major",
      src: { t: "Pop music has a new favourite chord progression", u: "https://www.youtube.com/watch?v=Tj0tkv2tNSo" },
      note: "The Axis chords again, reordered to start on IV." },
    { id: "doowop", group: "Pop & R&B", name: "Doo-wop", chords: ["I", "vi", "IV", "V"], tonality: "major", src: BENNETT7,
      note: "The 1950s changes underneath a lot of soul and R&B." },
    { id: "royal", group: "Pop & R&B", name: "Royal road", chords: ["IVmaj7", "V7", "iii7", "vi"], tonality: "major",
      src: { t: "Japan's favourite chord progression and why it works", u: "https://www.youtube.com/watch?v=6aezSL_GvZA" },
      note: "Lush and restless. The iii to vi move pulls hard toward minor." },
    { id: "jttou", group: "Pop & R&B", name: "Just the Two of Us", chords: ["bVImaj7", "V7", "i"], beats: [4, 4, 8], tonality: "minor",
      src: { t: "Songs that use the \"Just The Two Of Us\" chord progression", u: "https://www.youtube.com/watch?v=7vT0RxwL1HE" },
      note: "The core of the New Jack Swing sound. Watch the V7: the key's pentatonic clashes with it." },
    { id: "minor4", group: "Pop & R&B", name: "Minor four", chords: ["IV", "iv", "I"], beats: [4, 4, 8], tonality: "major",
      src: { t: "Songs that use the Minor 4 chord", u: "https://www.youtube.com/watch?v=tStINGVUbWo" },
      note: "IV turns minor for one bar before home. The borrowed chord changes one note." },
    { id: "backdoor", group: "Pop & R&B", name: "Backdoor", chords: ["iv", "bVII7", "I"], beats: [4, 4, 8], tonality: "major",
      src: { t: "Songs that use the Backdoor Progression", u: "https://www.youtube.com/watch?v=s1tDB79UEsQ" },
      note: "The gospel and Stevie Wonder way home: iv to bVII7 instead of V." },
    { id: "twofive", group: "Pop & R&B", name: "2-5-1", chords: ["ii", "V7", "I"], beats: [4, 4, 8], tonality: "major",
      src: { t: "Songs that use 2 5 1 chord progressions", u: "https://www.youtube.com/watch?v=6y-LoytFckI" },
      note: "The jazz and gospel front door home." },
    { id: "aeolian", group: "Pop & R&B", name: "Aeolian vamp", chords: ["i", "bVII", "bVI", "bVII"], tonality: "minor", src: BENNETT7,
      note: "Every chord fits the minor pentatonic. The easiest place to start riffing." },
    { id: "mixo", group: "Rock & blues", name: "Mixolydian vamp", chords: ["I", "bVII", "IV", "I"], tonality: "mixolydian", src: BENNETT7,
      note: "Also called the double plagal. Classic rock's favorite loop." },
    { id: "i5b74", group: "Rock & blues", name: "I–V–♭VII–IV", chords: ["I", "V", "bVII", "IV"], tonality: "mixolydian", src: BENNETT5,
      note: "Rock anthem changes that lean Mixolydian." },
    { id: "i454", group: "Rock & blues", name: "Blues rock I–IV–V–IV", chords: ["I", "IV", "V", "IV"], tonality: "major",
      src: { t: "Tunable: I–IV–V–IV Blues Rock", u: "https://tunableapp.com/chord-progressions/I-IV-V-IV-blues/" },
      note: "Three chords, back and forth. Try it in Blues style too." },
    { id: "ib7", group: "Rock & blues", name: "I–♭VII–I", chords: ["I", "bVII", "I"], beats: [4, 4, 8], tonality: "mixolydian",
      src: { t: "Tunable: I–♭VII–I Blues Rock", u: "https://tunableapp.com/chord-progressions/I-bVII-I-major/" },
      note: "A two-chord rock vamp. Lots of room to riff." },
    { id: "extplagal", group: "Rock & blues", name: "Extended plagal", chords: ["bVI", "bIII", "bVII", "IV", "I"], beats: [4, 4, 4, 4, 8], tonality: "blues", src: OMT,
      note: "A chain of IV-to-I moves falling by 4ths. Minor pentatonic over it is the rock sound." },
    { id: "b6b7", group: "Rock & blues", name: "♭VI–♭VII–I", chords: ["bVI", "bVII", "I"], beats: [4, 4, 8], tonality: "blues", src: OMT,
      note: "The big rock finish. Two borrowed chords climbing home." },
    { id: "epic", group: "Rock & blues", name: "Epic minor", chords: ["i", "bVI", "bIII", "bVII"], tonality: "minor",
      src: { t: "When did the Axis chord progression become so popular?", u: "https://www.youtube.com/watch?v=U8ImkF7FMPw" },
      note: "The Axis chords in their minor rotation, heavy and anthemic." },
    { id: "creep", group: "Rock & blues", name: "Creep", chords: ["I", "III", "IV", "iv"], tonality: "major",
      src: { t: "Songs that use the Creep chord progression", u: "https://www.youtube.com/watch?v=NyiEMdbfjG8" },
      note: "Two surprise chords: a major III and a minor iv. Both bend one note of the scale." },
    { id: "andalusian", group: "Rock & blues", name: "Andalusian cadence", chords: ["i", "bVII", "bVI", "V7"], tonality: "minor", src: BENNETT7,
      note: "Stepping down to a major V. The V is where the minor pentatonic stops working." },
    { id: "blues12", group: "Rock & blues", name: "12-bar blues", chords: ["I7", "I7", "I7", "I7", "IV7", "IV7", "I7", "I7", "V7", "IV7", "I7", "V7"], tonality: "blues",
      src: { t: "6 common chord progressions and why they work", u: "https://www.youtube.com/watch?v=v3YbEL-_eoI" },
      note: "The blues form. Minor pentatonic over dominant chords, blue notes on purpose." },
    /* ---- v4: more from David Bennett's chord progression videos ---- */
    { id: "purple", group: "Pop & R&B", name: "Purple Rain", chords: ["I", "vi", "V", "IV"], tonality: "major",
      src: { t: "Songs that use the Purple Rain chord progression", u: "https://www.youtube.com/watch?v=YEZzB2PpIQ8" },
      note: "Prince's loop: the Axis chords with the middle two swapped. One pentatonic covers it." },
    { id: "fourfive", group: "Pop & R&B", name: "4–5–6–1", chords: ["IV", "V", "vi", "I"], tonality: "major",
      src: { t: "Songs that use the 4-5-6-1 chord progression", u: "https://www.youtube.com/watch?v=2BS0saH0SYk" },
      note: "A climb that lands on vi before settling home. Same four chords as the Axis." },
    { id: "fourthree", group: "Pop & R&B", name: "4–3–2–1", chords: ["IV", "iii", "ii", "I"], tonality: "major",
      src: { t: "Songs that use the 4-3-2-1 Chord Progression", u: "https://www.youtube.com/watch?v=Vaavaj9DOGY" },
      note: "Stepping down the scale from IV to home, so each landing note sits a step lower." },
    { id: "onetwo", group: "Pop & R&B", name: "1–2–3–4", chords: ["I", "ii", "iii", "IV"], tonality: "major",
      src: { t: "Songs that use the 1-2-3-4 chord progression", u: "https://www.youtube.com/watch?v=eC4SEVRT9wE" },
      note: "Straight up the scale, and the landing notes climb with it." },
    { id: "coldplay", group: "Pop & R&B", name: "Coldplay's IV–I–V", chords: ["IV", "I", "V"], tonality: "major",
      src: { t: "Coldplay's go-to chord progression", u: "https://www.youtube.com/watch?v=Qd_qpdrl2i4" },
      note: "Three major chords and no minor chord, so it stays bright. A three-bar loop feels slightly off-balance." },
    { id: "circle", group: "Pop & R&B", name: "Circle of fifths", chords: ["vi", "ii", "V", "I"], tonality: "major",
      src: { t: "Songs that use the Circle of Fifths progression", u: "https://www.youtube.com/watch?v=-DQJmicTFGQ" },
      note: "Each root falls a 5th to the next. Jazz or Gospel style brings out the 2-5-1 at the end." },
    { id: "hmaxis", group: "Pop & R&B", name: "Harmonic minor Axis", chords: ["i", "bVI", "bIII", "V"], tonality: "minor",
      src: { t: "Songs that use the Harmonic Minor Axis progression", u: "https://www.youtube.com/watch?v=LjOKMNNo7HA" },
      note: "The minor Axis with a major V at the end. That V is where the key's pentatonic clashes." },
    { id: "pachelbel", group: "Pop & R&B", name: "Pachelbel's Canon", chords: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"], beats: [2, 2, 2, 2, 2, 2, 2, 2], tonality: "major",
      src: { t: "21 Songs that use Pachelbel's Canon chord progression", u: "https://www.youtube.com/watch?v=_PC6jwoHyOk" },
      note: "Eight chords, two per bar. Use short riffs, or switch to 2 bars per chord." },
    { id: "wonderwall", group: "Rock & blues", name: "Wonderwall", chords: ["i", "bIII", "bVII", "IV"], tonality: "dorian",
      src: { t: "Songs that use the Wonderwall chord progression", u: "https://www.youtube.com/watch?v=DfoM4EfHK0k" },
      note: "The Oasis verse loop, also called the plagal cascade. The major IV is the Dorian note, so land on its 3rd." },
    { id: "wheremind", group: "Rock & blues", name: "Where Is My Mind", chords: ["I", "vi", "III", "IV"], tonality: "major",
      src: { t: "Songs that use the \"Where Is My Mind\" progression", u: "https://www.youtube.com/watch?v=ttJlMFsL2ro" },
      note: "The Pixies loop. The major III raises one note of the scale by a half step." },
    { id: "electric", group: "Rock & blues", name: "She's Electric", chords: ["I", "III", "vi", "IV"], tonality: "major",
      src: { t: "Songs that use the “She’s Electric” chord progression", u: "https://www.youtube.com/watch?v=mUYgS4IP_TU" },
      note: "The III works as a dominant pulling into vi, so it gets its own scale." },
    { id: "eightdays", group: "Rock & blues", name: "Eight Days a Week", chords: ["I", "II", "IV", "I"], tonality: "major",
      src: { t: "the \"Eight Days a Week\" chord progression", u: "https://www.youtube.com/watch?v=5ANjO8ypYfQ" },
      note: "A bright Beatles loop of all major chords. The major II adds a Lydian lift." },
    { id: "bluesrock", group: "Rock & blues", name: "Blues rock I–♭III–IV", chords: ["I", "bIII", "IV"], beats: [4, 4, 8], tonality: "blues",
      src: { t: "Songs that use the Blues Rock Chord Progression", u: "https://www.youtube.com/watch?v=kVxA0EouxkQ" },
      note: "Major I, a borrowed ♭III, then IV. The minor pentatonic rides right over it." },
    { id: "runhill", group: "Rock & blues", name: "Running Up That Hill", chords: ["bVI", "bVII", "i"], beats: [4, 4, 8], tonality: "minor",
      src: { t: "Songs that use the Running Up That Hill chord progression", u: "https://www.youtube.com/watch?v=6TUUe-FrPOI" },
      note: "Kate Bush's climb into minor. Every chord fits the minor pentatonic." },
    /* ---- v5: '60s classics ---- */
    { id: "risingsun", group: "'60s classics", name: "House of the Rising Sun", chords: ["i", "bIII", "IV", "bVI", "i", "bIII", "V", "V"], beats: [2, 2, 2, 2, 2, 2, 2, 2], tonality: "minor",
      src: { t: "Hooktheory: House of the Rising Sun", u: "https://www.hooktheory.com/theorytab/view/the-animals/house-of-the-rising-sun" },
      note: "The Animals, 1964. Minor, with a major IV and a major V, so two chords borrow notes from outside the minor pentatonic." },
    { id: "louie", group: "'60s classics", name: "Louie Louie", chords: ["I", "IV", "v", "IV"], tonality: "mixolydian",
      src: { t: "Hooktheory: Louie Louie", u: "https://www.hooktheory.com/theorytab/view/the-kingsmen/louie-louie" },
      note: "The Kingsmen, 1963. A Mixolydian garage-rock loop with a minor v." },
    { id: "twist", group: "'60s classics", name: "Twist and Shout", chords: ["I", "IV", "V"], beats: [2, 2, 4], tonality: "major",
      src: { t: "Hooktheory: Twist and Shout", u: "https://www.hooktheory.com/theorytab/view/the-beatles/twist-and-shout" },
      note: "The Isley Brothers and the Beatles, 1962 to 1963. Three chords in one bar and a held V. Short riffs only." },
    { id: "brown", group: "'60s classics", name: "Brown Eyed Girl", chords: ["I", "IV", "I", "V7"], tonality: "major",
      src: { t: "Hooktheory: Brown Eyed Girl", u: "https://www.hooktheory.com/theorytab/view/van-morrison/brown-eyed-girl" },
      note: "Van Morrison, 1967. Bright and simple. The V7 at the end sets up each return home." },
    { id: "california", group: "'60s classics", name: "California Dreamin'", chords: ["i", "bVII", "bVI", "bVII", "V"], beats: [2, 2, 2, 2, 8], tonality: "minor",
      src: { t: "Hooktheory: California Dreamin'", u: "https://www.hooktheory.com/theorytab/view/mamas-and-the-papas/california-dreamin" },
      note: "The Mamas and the Papas, 1965. Walks down and back up, then holds the V. Most charts play that last chord as a sus4 resolving to major (Hooktheory marks it minor), so it's major here." },
    { id: "grapevine", group: "'60s classics", name: "Grapevine", chords: ["i", "IV7"], tonality: "dorian",
      src: { t: "Hooktheory: I Heard It Through the Grapevine", u: "https://www.hooktheory.com/theorytab/view/marvin-gaye/i-heard-it-through-the-grapevine" },
      note: "Marvin Gaye, 1968. A two-chord Dorian soul vamp: lots of room to riff, and the IV7's 3rd is the note to land on." },
    { id: "dock", group: "'60s classics", name: "Dock of the Bay", chords: ["I", "III", "IV", "II"], tonality: "major",
      src: { t: "Hooktheory: Sittin' On The Dock of the Bay", u: "https://www.hooktheory.com/theorytab/view/otis-redding/sittin-on-the-dock-of-the-bay" },
      note: "Otis Redding, 1968. Two major chords from outside the key (III and II), each raising one note of the scale." },
    { id: "heyjude", group: "'60s classics", name: "Hey Jude outro", chords: ["I", "bVII", "IV", "I"], tonality: "mixolydian",
      src: { t: "Hooktheory: Hey Jude", u: "https://www.hooktheory.com/theorytab/view/the-beatles/hey-jude" },
      note: "The Beatles, 1968. The “na na na” coda switches to Mixolydian. A great loop for long, free ad-libs." },
    /* ---- v6: '50s rock and roll and doo-wop ---- */
    { id: "quickchange", group: "'50s classics", name: "Quick-change 12-bar", chords: ["I7", "IV7", "I7", "I7", "IV7", "IV7", "I7", "I7", "V7", "IV7", "I7", "V7"], tonality: "blues",
      src: { t: "Guitar Noise: Standard twelve-bar blues and the quick change", u: "https://www.guitarnoise.com/guide/standard-twelve-bar-blues/" },
      note: "The rock and roll 12-bar with a jump to IV in bar 2. The early change keeps the first line moving." },
    { id: "doowopii", group: "'50s classics", name: "Doo-wop with ii", chords: ["I", "vi", "ii", "V"], tonality: "major",
      src: { t: "Wikipedia: '50s progression (I–vi–ii–V variant)", u: "https://en.wikipedia.org/wiki/%2750s_progression" },
      note: "The '50s progression with ii in place of IV, so the roots fall by 5ths into V. Smoother and a little jazzier." },
    { id: "sleepwalk", group: "'50s classics", name: "Sleep Walk", chords: ["I", "vi", "iv", "V"], tonality: "major",
      src: { t: "Hooktheory: Sleep Walk", u: "https://www.hooktheory.com/theorytab/view/santo-and-johnny/sleep-walk" },
      note: "Santo & Johnny, 1959. Doo-wop with a borrowed minor iv, which lowers one note for a dreamy, sad turn." },
    /* ---- v6: '70s classics ---- */
    { id: "sweethome", group: "'70s classics", name: "Sweet Home Alabama", chords: ["I", "bVII", "IV"], beats: [4, 4, 8], tonality: "mixolydian",
      src: { t: "Hooktheory: Sweet Home Alabama", u: "https://www.hooktheory.com/theorytab/view/lynyrd-skynyrd/sweet-home-alabama" },
      note: "Lynyrd Skynyrd, 1974. A Mixolydian three-chord loop, so the minor pentatonic a 5th above the key fits." },
    { id: "heavensdoor", group: "'70s classics", name: "Knockin' on Heaven's Door", chords: ["I", "V", "ii", "I", "V", "IV"], beats: [4, 4, 8, 4, 4, 8], tonality: "major",
      src: { t: "Hooktheory: Knockin' On Heaven's Door", u: "https://www.hooktheory.com/theorytab/view/bob-dylan/knockin-on-heavens-door" },
      note: "Bob Dylan, 1973. Two phrases: one ends on ii, the other on IV. Slow and spacious, good for long held landings." },
    { id: "hotelcal", group: "'70s classics", name: "Hotel California", chords: ["i", "V", "bVII", "IV", "bVI", "bIII", "iv", "V"], tonality: "minor",
      src: { t: "Hooktheory: Hotel California", u: "https://www.hooktheory.com/theorytab/view/eagles/hotel-california" },
      note: "Eagles, 1976. Eight chords with a major V and a major IV, so chord by chord pays off here." },
    { id: "whatsgoingon", group: "'70s classics", name: "What's Going On", chords: ["Imaj7", "vi"], tonality: "major",
      src: { t: "Hooktheory: What's Going On", u: "https://www.hooktheory.com/theorytab/view/marvin-gaye/whats-going-on" },
      note: "Marvin Gaye, 1971. A two-chord soul vamp that sounds best in R&B or Gospel style." },
    { id: "sunshine", group: "'70s classics", name: "Ain't No Sunshine", chords: ["i", "v", "bVII", "i"], tonality: "minor",
      src: { t: "Hooktheory: Ain't No Sunshine", u: "https://www.hooktheory.com/theorytab/view/bill-withers/aint-no-sunshine" },
      note: "Bill Withers, 1971. All minor-key chords, so the minor pentatonic fits every one." },
    { id: "lovely", group: "'70s classics", name: "Isn't She Lovely", chords: ["vi", "II7", "V", "I"], tonality: "major",
      src: { t: "Hooktheory: Isn't She Lovely", u: "https://www.hooktheory.com/theorytab/view/stevie-wonder/isnt-she-lovely" },
      note: "Stevie Wonder, 1976. The II7 is a secondary dominant pulling to V, so it raises one note of the scale." }
  ];

  /* ---- Vocabulary: patterns beyond the five blocks (general, not from the video) ---- */
  const q = .25;
  D.VOCAB = [
    { id: "cas3", name: "Cascade in 3s", kind: "pent", steps: [2, 1, 0, 1, 0, -1, 0, -1, -2, -1, -2, -3], beats: [q, q, q, q, q, q, q, q, q, q, q, 1.25], land: true, c: "var(--pink)",
      desc: "The Quick Dip, repeated one step lower each time. Groups of three against a 4/4 pulse give it a rolling feel." },
    { id: "cas4", name: "Cascade in 4s", kind: "pent", steps: [3, 2, 1, 0, 2, 1, 0, -1, 1, 0, -1, -2], beats: [q, q, q, q, q, q, q, q, q, q, q, 1.25], land: true, c: "var(--orange)",
      desc: "Four-note groups falling down the scale. This is the long run you hear at the end of big phrases." },
    { id: "turn", name: "Pentatonic turn", kind: "pent", steps: [0, 1, 0, -1, 0], beats: [q, q, q, q, 1], land: true, c: "var(--green)",
      desc: "Circle a note: up one, back, down one, back. Small, quick, and everywhere in R&B." },
    { id: "climb", name: "Pentatonic climb", kind: "pent", steps: [-3, -2, -1, 0, 1, 2], beats: [q, q, q, q, q, 1], land: true, c: "var(--blue)",
      desc: "A straight run up the scale into a held note. Use it to lift into a high line." },
    { id: "trip3", name: "Triplet Quick Dip Trip", kind: "pent", steps: [0, -1, -2, -3], beats: [1 / 3, 1 / 3, 1 / 3, 1], land: true, c: "var(--yellow)",
      desc: "Her Quick Dip Trip, regrouped as a triplet. Same notes, lazier and more laid-back." },
    { id: "encl", name: "Enclosure", kind: "encl", land: true, beats: [.5, .5, 1], c: "var(--pink)",
      desc: "Approach the target from a scale step above, then a half step below, then land. It makes any chord tone sound intentional." },
    { id: "blue", name: "Blue-note slide", kind: "semi", ctx: "major", semis: [3, 4, 2, 0], beats: [.125, .375, .25, 1], c: "var(--blue)",
      desc: "Slide from the minor 3rd into the major 3rd, then step down to the root. The classic bluesy scoop over a major chord." },
    { id: "gospel", name: "Gospel descent", kind: "semi", ctx: "major", semis: [12, 9, 7, 4, 2, 0], beats: [q, q, q, q, q, 1], c: "var(--green)",
      desc: "Down the major pentatonic from the octave: 8, 6, 5, 3, 2, 1. The sound of a choir run." },
    { id: "arpm7", name: "Minor 7 arpeggio run", kind: "semi", ctx: "minor", semis: [0, 3, 7, 10, 12, 10, 7, 3, 0], beats: [q, q, q, q, q, q, q, q, 1], c: "var(--orange)",
      desc: "Up and down the chord tones of a minor 7. It trains your ear to hear where the chord lives." },
    { id: "arpmaj7", name: "Major 7 arpeggio run", kind: "semi", ctx: "major", semis: [0, 4, 7, 11, 12, 11, 7, 4, 0], beats: [q, q, q, q, q, q, q, q, 1], c: "var(--yellow)",
      desc: "The same idea over a major 7. The 7th a half step under the octave is the neo-soul color." },
    /* v4 licks */
    { id: "flip", name: "Neighbor flip", kind: "pent", steps: [1, 0, 1, 0, -1, 0], beats: [q, q, q, q, q, 1.25], land: true, c: "var(--pink)",
      desc: "Flip between two neighboring notes, dip one step, and come back to land. It's the quick shimmer singers put on a held word." },
    { id: "seq3", name: "Rising 3s", kind: "pent", steps: [-2, -1, 0, -1, 0, 1, 0, 1, 2], beats: [q, q, q, q, q, q, q, q, 1], land: true, c: "var(--blue)",
      desc: "The cascade turned upward: three-note groups climbing the pentatonic, each one starting a step higher." },
    { id: "bluesturn", name: "Blue-note turn", kind: "semi", ctx: "minor", semis: [7, 6, 5, 3, 0], beats: [q, q, q, q, 1], c: "var(--orange)",
      desc: "Slide down from the 5th through the ♭5 blue note to the root. The ♭5 passes quickly, so it adds grit without sounding wrong." },
    /* v4 scale runs */
    { id: "pentud", cat: "run", name: "Pentatonic up and down", kind: "pent", steps: [0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0], beats: [.5, .5, .5, .5, .5, .5, .5, .5, .5, .5, 1], land: true, c: "var(--green)",
      desc: "Up the minor pentatonic to the octave and back down, one note per half beat. Keep every note the same size." },
    { id: "pentfall", cat: "run", name: "Pentatonic fall", kind: "pent", steps: [5, 4, 3, 2, 1, 0], beats: [q, q, q, q, q, 1], land: true, c: "var(--yellow)",
      desc: "A quick run down the pentatonic from the octave into a held landing note, the mirror of the climb." },
    { id: "fivemin", cat: "run", name: "Five-note minor run", changesName: "Five-note scale run", kind: "scale", ctx: "minor", steps: [0, 1, 2, 3, 4, 3, 2, 1, 0], beats: [.5, .5, .5, .5, .5, .5, .5, .5, 1], land: true, c: "var(--pink)",
      desc: "1 2 ♭3 4 5 4 ♭3 2 1 of the natural minor scale. Over a progression it runs on each chord's own scale instead." },
    { id: "fivemaj", cat: "run", name: "Five-note major run", kind: "scale", ctx: "major", steps: [0, 1, 2, 3, 4, 3, 2, 1, 0], beats: [.5, .5, .5, .5, .5, .5, .5, .5, 1], c: "var(--orange)",
      desc: "1 2 3 4 5 4 3 2 1 of the major scale, on the relative major of your riff key so it shares the same notes." },
    { id: "octmin", cat: "run", name: "Natural minor octave", kind: "scale", ctx: "minor", steps: [0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0], beats: [.5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, 1], c: "var(--blue)",
      desc: "The full natural minor scale up an octave and back. Save it for when the five-note run feels easy." }
  ];

  D.METHODS = [
    { id: "listen", name: "Listen", desc: "Hear it twice at your tempo." },
    { id: "doo", name: "Doo first", desc: "Three slow rounds on “doo,” then one on “ah.” Consonants keep the notes clean." },
    { id: "chunk", name: "Chunks", desc: "Each half twice, slowly, then the whole thing." },
    { id: "back", name: "Build from the end", desc: "Last two notes, then last three, and so on until you have the whole riff." },
    { id: "accent", name: "Move the accent", desc: "Each round leans on a different note, so no note gets swallowed." },
    { id: "rhythm", name: "Rhythm swap", desc: "As written, straight sixteenths, triplets, then swung." },
    { id: "speed", name: "Speed up", desc: "Four rounds climbing toward 100 bpm." }
  ];

  if (typeof module !== "undefined" && module.exports) module.exports = D;
  else { root.VL = root.VL || {}; root.VL.data = D; }
})(typeof window !== "undefined" ? window : globalThis);
